CREATE TABLE IF NOT EXISTS NEW_HIRE_ACCOUNT (
    NEW_HIRE_ACCOUNT_ID varchar PRIMARY KEY,
    EMAIL_ADDRESS varchar(256),
    CREATED_INSTANT timestamp,
    CHANGED_INSTANT timestamp,
    STATE varchar(128)
);
