CREATE TABLE IF NOT EXISTS NEW_HIRE_ACCOUNT (
    NEW_HIRE_ACCOUNT_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    EMAIL_ADDRESS VARCHAR(256) NOT NULL,
    CREATED_INSTANT TIMESTAMP NOT NULL,
    CHANGED_INSTANT TIMESTAMP NOT NULL,
    STATE VARCHAR(128) NOT NULL
);
