CREATE TABLE IF NOT EXISTS NEW_HIRE_CREDENTIALS (
    NEW_HIRE_CREDENTIALS_ID varchar PRIMARY KEY,
    NEW_HIRE_ACCOUNT_ID varchar,
    SALT varchar(256),
    VERIFIER VARCHAR(256),
    CONSTRAINT FK_NEW_HIRE
        FOREIGN KEY(NEW_HIRE_ACCOUNT_ID)
        REFERENCES NEW_HIRE_ACCOUNT(NEW_HIRE_ACCOUNT_ID)
        ON DELETE CASCADE
);