CREATE TABLE IF NOT EXISTS NEW_HIRE_CREDENTIALS (
    NEW_HIRE_CREDENTIALS_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NEW_HIRE_ACCOUNT_ID UUID UNIQUE NOT NULL,
    SALT VARCHAR(256) NOT NULL,
    VERIFIER VARCHAR(256) NOT NULL,
    CONSTRAINT FK_NEW_HIRE
        FOREIGN KEY(NEW_HIRE_ACCOUNT_ID)
        REFERENCES NEW_HIRE_ACCOUNT(NEW_HIRE_ACCOUNT_ID)
        ON DELETE CASCADE
);