CREATE TABLE IF NOT EXISTS NEW_HIRE_AUTHORIZATION_CODE (
    NEW_HIRE_AUTHORIZATION_CODE_ID varchar PRIMARY KEY,
    NEW_HIRE_ACCOUNT_ID varchar,
    SALT varchar(256),
    VERIFIER varchar(256),
    PURPOSE varchar(128),
    SOURCE varchar(128),
    ISSUED_INSTANT timestamp,
    TIME_TO_LIVE bigint,
    CONSUMED_INSTANT timestamp,
    CONSTRAINT FK_NEW_HIRE
        FOREIGN KEY(NEW_HIRE_ACCOUNT_ID)
        REFERENCES NEW_HIRE_ACCOUNT(NEW_HIRE_ACCOUNT_ID)
        ON DELETE CASCADE
);