CREATE TABLE IF NOT EXISTS NEW_HIRE_AUTHORIZATION_CODE (
    NEW_HIRE_AUTHORIZATION_CODE_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NEW_HIRE_ACCOUNT_ID UUID NOT NULL,
    SALT VARCHAR(256) NOT NULL,
    VERIFIER VARCHAR(256) NOT NULL,
    PURPOSE VARCHAR(128) NOT NULL,
    SOURCE VARCHAR(128) NOT NULL,
    ISSUED_INSTANT TIMESTAMP NOT NULL,
    TIME_TO_LIVE BIGINT NOT NULL,
    CONSUMED_INSTANT TIMESTAMP,
    CONSTRAINT FK_NEW_HIRE
        FOREIGN KEY(NEW_HIRE_ACCOUNT_ID)
        REFERENCES NEW_HIRE_ACCOUNT(NEW_HIRE_ACCOUNT_ID)
        ON DELETE CASCADE
);