version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: checkins@objectcomputing.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "1080:80"
    container_name: pgadmin
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    container_name: sonarqube
