package com.objectcomputing.checkins.security.permissions;

public enum Permissions {
    CAN_VIEW_FEEDBACK_REQUEST,
    CAN_CREATE_FEEDBACK_REQUEST,
    CAN_DELETE_FEEDBACK_REQUEST,
    CAN_VIEW_FEEDBACK_ANSWER,
    CAN_DELETE_ORGANIZATION_MEMBERS,
    CAN_CREATE_ORGANIZATION_MEMBERS,
    CAN_VIEW_ROLE_PERMISSIONS,
    CAN_VIEW_PERMISSIONS
}