title: Check-Ins
logo: /assets/img/logo.png
description: Check-Ins is an open-source team engagement platform designed to empower you and your colleagues to collaborate, grow, and thrive.
theme: just-the-docs
baseurl: /check-ins
url: https://objectcomputing.github.io
repository: objectcomputing/check-ins # for github-metadata

permalink: pretty

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
