title: Check-Ins
logo: /web-ui/public/img/ocicube-color.png
description: Check-Ins is an open-source team engagement platform for organizations looking to create meaningful, long-term relationships with team members.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

