package com.objectcomputing.checkins.security.permissions;

public enum Permissions {
    CAN_VIEW_FEEDBACK_REQUEST,
    CAN_CREATE_FEEDBACK_REQUEST,
    CAN_DELETE_FEEDBACK_REQUEST,
    CAN_VIEW_FEEDBACK_ANSWER,
    CAN_DELETE_ORGANIZATION_MEMBERS,
    CAN_CREATE_ORGANIZATION_MEMBERS,
    CAN_VIEW_ROLE_PERMISSIONS,
    CAN_ASSIGN_ROLE_PERMISSIONS,
    CAN_VIEW_PERMISSIONS,
    CAN_VIEW_SKILLS_REPORT,
    CAN_VIEW_RETENTION_REPORT,
    CAN_VIEW_ANNIVERSARY_REPORT,
    CAN_VIEW_BIRTHDAY_REPORT,
    CAN_VIEW_PROFILE_REPORT,
    CAN_CREATE_CHECKINS,
    CAN_VIEW_CHECKINS,
    CAN_UPDATE_CHECKINS,
    CAN_VIEW_CHECKINS_ELEVATED,
    CAN_CREATE_CHECKINS_ELEVATED,
    CAN_UPDATE_CHECKINS_ELEVATED
}