package com.objectcomputing.checkins.security.permissions;
/*
    CAN_CREATE_,
    CAN_DELETE_,
    CAN_VIEW_,
 */

public enum Permissions {
    // Check-ins
    CAN_CREATE_CHECKIN,
    CAN_DELETE_CHECKIN,
    CAN_VIEW_CHECKIN,

    //Check-in Documents and Private Notes
    CAN_CREATE_SENSITIVE_DATA,
    CAN_DELETE_SENSITIVE_DATA,
    CAN_VIEW_SENSITIVE_DATA,

    // Demographics
    CAN_CREATE_DEMOGRAPHIC,
    CAN_DELETE_DEMOGRAPHIC,
    CAN_VIEW_DEMOGRAPHIC,

    // Employee Hours
    CAN_UPLOAD_HOURS,
    CAN_VIEW_HOURS,

    // Feedback
    CAN_CREATE_FEEDBACK_ANSWER,
    CAN_CREATE_FEEDBACK_REQUEST,
    CAN_CREATE_FEEDBACK_TEMPLATE,
    CAN_DELETE_FEEDBACK_REQUEST,
    CAN_DELETE_FEEDBACK_TEMPLATE,
    CAN_VIEW_FEEDBACK_ANSWER,
    CAN_VIEW_FEEDBACK_REQUEST,
    CAN_VIEW_FEEDBACK_SUGGESTION,
    CAN_VIEW_FEEDBACK_TEMPLATE,

    // Files
    CAN_DELETE_FILES,
    CAN_DOWNLOAD_FILES,
    CAN_UPLOAD_FILES,
    CAN_VIEW_FILES,

    // GitHub
    CAN_CREATE_GITHUB_ISSUE,

    // Guilds
    CAN_CREATE_GUILD,
    CAN_DELETE_GUILD,
    CAN_VIEW_GUILD,

    // Members
    CAN_CREATE_MEMBER,
    CAN_CREATE_MEMBER_SKILL,
    CAN_CREATE_RETENTION_REPORT,
    CAN_DELETE_MEMBER,
    CAN_DELETE_MEMBER_SKILL,
    CAN_VIEW_ANNIVERSARY,
    CAN_VIEW_CURRENT_USER,
    CAN_VIEW_MEMBER,
    CAN_VIEW_MEMBER_BDAY,
    CAN_VIEW_MEMBER_SKILL,

    // Notes
    CAN_CREATE_PRIVATE_NOTE,
    CAN_VIEW_PRIVATE_NOTE,

    // Opportunities
    CAN_CREATE_OPPORTUNITIES,
    CAN_DELETE_OPPORTUNITIES,
    CAN_VIEW_OPPORTUNITIES,

    // Organization Members
    CAN_CREATE_ORGANIZATION_MEMBERS,
    CAN_DELETE_ORGANIZATION_MEMBERS,

    // Permissions
    CAN_VIEW_PERMISSIONS,

    // Pulse Response
    CAN_CREATE_PULSE_RESPONSE,
    CAN_VIEW_PULSE_RESPONSE,

    // Questions
    CAN_CREATE_QUESTION,
    CAN_CREATE_QUESTION_CATEGORY,
    CAN_DELETE_QUESTION_CATEGORY,
    CAN_VIEW_QUESTION,
    CAN_VIEW_QUESTION_CATEGORY,

    // Request Notifications
    CAN_VIEW_REQUESTS,

    // Roles
    CAN_CREATE_ROLE,
    CAN_DELETE_ROLE,
    CAN_VIEW_ROLE,
    CAN_VIEW_ROLE_PERMISSIONS,

    // Settings
    CAN_CREATE_SETTING,
    CAN_DELETE_SETTING,
    CAN_VIEW_SETTING,

    // Skills
    CAN_CREATE_SKILL,
    CAN_DELETE_SKILL,
    CAN_VIEW_SKILL,

    // Surveys
    CAN_CREATE_SURVEY,
    CAN_DELETE_SURVEY,
    CAN_VIEW_SURVEY,

    // Tags
    CAN_CREATE_TAG,
    CAN_DELETE_TAG,
    CAN_VIEW_TAG,

    // Teams
    CAN_CREATE_TEAM,
    CAN_DELETE_TEAM,
    CAN_VIEW_TEAM
}