name: Cypress Test - Feature / Bug
on:
  push:
    branches:
      - 'feature-934/implementing-cypress-in-the-development-environment'
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle package
        run: ./gradlew assemble
      - name: Build docker image
        run: ./gradlew dockerBuild
      - name: Docker images
        run: docker images
      - name: Run docker container
        run: ./gradlew dockerRun
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: web-ui
          build: yarn build
          start: yarn start
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Gradle docker stop
        run: ./gradlew dockerStop
