name: Gradle Build Native Image - Feature / Bug
on:
  push:
    branches:
      - 'feature-**/*'
      - 'bugfix-**/*'
      - 'chore-**/*'
      - 'doc-**/*'
      - 'hotfix-**/*'
      - 'dependabot/**/*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Set up GraalVM 21
        uses: graalvm/setup-graalvm@v1.1.8
        with:
          distribution: 'graalvm'
          java-version: '21'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build native image
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: nativeCompile
